### PR TITLE
Declare dependency on Moose

### LINKED ISSUE #1: Undeclared dependency on Moose
This module requires Moose, but this dependency is not declared.  This will cause the tests to fail of Moose is not installed.

### PR DESCRIPTION
**Pull request by mschout**
Fixes #1

### CODE REVIEW

**Comment by mschout** [comment]
Hey Jonathan.

I saw in the RT queue that you might be looking for someone to adopt this module.  I'll be more than happy to take it over if you are open to that.  My PAUSE id is MSCHOUT if you are interested.  We are actively using this module in production.

**Comment by jonswar** [comment]
Sure! It's been a few years so remind me what I need to do. :)

**Comment by mschout** [comment]
Just log in to https://pause.perl.org, then go to "Change Permissions".  You can just add my pause id (MSCHOUT) as a COMAINT and thats sufficient.  Or you can do "transfer primary ownership" if you want.  Either way is fine, but if you keep primary you maintain the option to revoke  COMAINT from me down the line.  Its up to you really. Either way allows me to upload new dists.

**Comment by jonswar** [comment]
Were these the right packages?
MSCHOUT was already a co-maintainer of CHI::Driver::BerkeleyDB: skipping
MSCHOUT was already a co-maintainer of CHI::Driver::BerkeleyDB::Test::Class: skipping
MSCHOUT was already a co-maintainer of CHI::Driver::BerkeleyDB::Test::InternalOnly: skipping
MSCHOUT was already a co-maintainer of CHI::Driver::BerkeleyDB::Util: skipping
MSCHOUT was already a co-maintainer of CHI::Driver::BerkeleyDB::t::CHIDriverTests: skipping
MSCHOUT was already a co-maintainer of CHI::Driver::BerkeleyDB::t::Sanity: skipping

**Comment by mschout** [comment]
Looks like it.  I'll upload a dist today and let you know if there are any issues.

**Comment by mschout** [comment]
0.04 has just been uploaded, and PAUSE indexed it, so we're all set.  I'm closing this issue.  Thanks!

**Pull request closed without merging**
